DairyManagement/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken.views import obtain_auth_token
app_name = 'DairyManagement'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'register/',views.register, name='register'),
    url('login/', views.loginPage, name="login"),
    url('logout/', views.logoutUser, name="logout"),
    url(r'^user/', views.userPage, name='user'),
    url(r'^addProduct/', views.add_product, name='addProduct'),
    url(r'^options/', views.show_options, name='options'),
    url(r'^milkData/', views.add_milk, name='milkData'),
    url(r'^products/', views.products, name='products'),
    url(r'^total/', views.SalaryModel, name='total'),
    url(r'^margin/', views.margin, name='margin'),
    url(r'^sales/(?P<pk>\d+)/$', views.add_user_sales, name='sales'),
    url(r'^monthly_total/', views.get_total_month, name='monthlyTotal'),
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

steady/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("DairyManagement.urls" , namespace='DairyManagement')),
]

DairyManagement/models.py
# imports
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.contrib.auth.models import AbstractUser
from django.conf import settings
# class create profile

class UserProfile(models.Model):
    profile_name = models.OneToOneField(User, unique=True, on_delete=models.CASCADE, null=True, related_name='my_profile')
    # email_field = models.EmailField(null=True, unique=True)
    User._meta.get_field('email')._unique = True


    # save user profile
    def __str__(self):
        return str(self.profile_name)

    # model class signal upon creation
    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):

            if created:
                UserProfile.objects.create(profile_name=instance)
                print('profile created')

    # save user instance
    @receiver(post_save, sender=User)
    def save_profile(sender, instance, **kwargs):
            instance.profile.save()
            print(instance.profile.save())

    # back up
    def save_profile(self, *args, **kwargs):
        super().save(*args, **kwargs)
        print('profile profile')

    # retrieve profiles
    @classmethod
    def get_profile(cls):
        profile = UserProfile.objects.all()
        return profile
# model for data collection

class Project(models.Model):
    MONTH_OF_THE_YEAR = (
        ('January', 'January'),
        ('February', 'February'),
        ('March', 'March'),
        ('April', 'April'),
        ('May', 'May'),
        ('June', 'June'),
        ('July', 'July'),
        ('August', 'August'),
        ('September', 'September'),
        ('October', 'October'),
        ('November', 'November'),
        ('Decemeber', 'Decemeber')
    )
    posted_by = models.ForeignKey(User, null=True, blank=False, on_delete=models.CASCADE, related_name='my_user')
    added_month = models.CharField(max_length=10, null=True, blank=False, choices=MONTH_OF_THE_YEAR)
    profile = models.ForeignKey(UserProfile, null=True, blank=False,  on_delete=models.CASCADE, related_name='his_user')
    product = models.CharField(max_length=20, null=True, blank=False , unique=True)
    product_item = models.CharField(max_length=20, null=True, blank=False )
    quantity = models.IntegerField(null=True, blank=False)
    price = models.IntegerField(null=True, blank=False )
    total = models.IntegerField(editable=True, null=True, blank=False)
    date_created = date_created = models.DateTimeField(auto_now_add=True, null=True, blank=False)

    def __str__(self):
        return str(self.profile)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.total = self.price * self.quantity
        super().save(*args, **kwargs)

    @classmethod
    def get_projects(cls):
        projects = Project.objects.all()
        return projects

    @classmethod
    def find_project(cls,search_term):
        project = Project.objects.filter(product__icontains=search_term)

        return project

class MadeSale(models.Model):
    MONTH_OF_THE_YEAR = (
        ('January', 'January'),
        ('February', 'February'),
        ('March', 'March'),
        ('April', 'April'),
        ('May', 'May'),
        ('June', 'June'),
        ('July', 'July'),
        ('August', 'August'),
        ('September', 'September'),
        ('October', 'October'),
        ('November', 'November'),
        ('Decemeber', 'Decemeber')
    )
    month_of_sales =  models.CharField(max_length=10, null=False, blank=False, choices=MONTH_OF_THE_YEAR)
    juror = models.ForeignKey(User, null=True, blank=False, on_delete=models.CASCADE,)
    profile = models.ForeignKey(UserProfile, null=True, blank=False,  on_delete=models.CASCADE, related_name='profile3')
    project = models.ForeignKey(Project, to_field='product', null=True, blank=False, on_delete=models.CASCADE)
    margin = models.IntegerField(null=True, blank=False)
    sales = models.IntegerField( null=True, blank=False)
    comment = models.CharField(max_length=200, null=True, blank=False)
    date_created = date_created = models.DateTimeField(auto_now_add=True, null=True, blank=False)

    def __str__(self):
        return str(self.profile)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.margin = self.sales - Project.objects.last().total
        if self.sales > self.margin:

            self.margin =  self.margin 
        else:
            -self.margin
        return super().save( *args, **kwargs)

    @classmethod
    def get_sales(cls):
        accounts = MadeSale.objects.all()
        return accounts

class MilkCollection(models.Model):
    Day_Collected = (
        ("monday", "Monday"),
        ("tuesday", "Tuesday"),
        ("wednesday", "Wednesday"),
        ("thursday", "Thursday"),
        ("friday", "Friday"),
        ('saturday', "Saturday"),
        ('sunday', "Sunday"),
    )

    juror = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    profile = models.ForeignKey(UserProfile, null=True, blank=False,  on_delete=models.CASCADE, related_name='profile2')
    day_of_the_week = models.CharField(choices=Day_Collected, max_length=10)
    morning_litres = models.FloatField(null=True, default=0.00)
    evening_litres = models.FloatField(null=True, default=0.00)
    total_litres = models.FloatField(null=True, default=0.00)
    price_per_litre = models.FloatField(max_length=30, null=True, blank=False)
    price_per_month = models.FloatField(null=True)
    total = models.FloatField(null=True)

    def __str__(self):
        return str(self.profile)
        
    def save(self, *args, **kwargs):
        self.price_per_month = self.morning_litres + self.evening_litres * price_per_litre * 30.00
        super().save(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.total_litres = self.morning_litres + self.evening_litres
        super().save(*args, **kwargs)

    def get_total(self, *args, **kwargs):
        self.total = self.morning_litres + self.evening_litres * price_per_litre * 30.00
        super().save(*args, **kwargs)

DairyManagement/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import *
from django.contrib.auth.models import AbstractBaseUser
from django.contrib import messages



class RegistrationForm(UserCreationForm):
    email = forms.EmailField(label="Email Address", required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

        def clean_email(self):
            email = self.cleaned_data.get("email")
            if User.objects.filter(email=email).exists():
                print("email exists")
            return self.cleaned_data


class ProductForm(forms.ModelForm):
    class Meta:
        model = Project
        fields =['product', 'product_item', 'quantity', 'price', 'added_month']

class SalesForm(forms.ModelForm):
    class Meta:
        model = MadeSale
        fields =['project', 'month_of_sales', 'sales']

class MilkCollectionForm(forms.ModelForm):
    class Meta:
        model = MilkCollection
        fields = ['day_of_the_week', 'evening_litres', 'morning_litres','price_per_litre']

DairyManagement/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import *
from .models import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
import numpy as np
# login view page
def home(request):
    return render(request, 'home.html', {})

# registration view
def register(request):
    form = RegistrationForm()
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            email = form.validate_unique()
            messages.success(request, "Account was created for " + username)
            return redirect ('DairyManagement:login')

    context = {'form': form}
    return render(request, 'register.html', context)

# login view
def loginPage(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("DairyManagement:user")
        else:
            messages.info(request, "Username or password is incorrect")

    context = {}
    return render(request, 'login.html', context)

# logout view
def logoutUser(request):
    logout(request)
    messages.success(request, "Logout Successful")
    return redirect('home')

# after login userpage
@login_required
def userPage(request):
    context = {}
    return render(request, 'user.html', context)

# user products
@login_required
def add_product(request):
    current_user = request.user
    profiles = UserProfile.get_profile()
    productinfo = request.POST.get("product")
    for profile in profiles: 
        if profile.profile_name.id == current_user.id:
            if request.method == 'POST':
                form = ProductForm(request.POST)
                if form.is_valid():
                    upload = form.save(commit=False)
                    upload.posted_by = current_user
                    upload.profile = profile
                    upload.save()
                    messages.success(request, f'Hello! {productinfo} has successfully been updated' )
                    return redirect('addProduct')
            else:
                form = ProductForm()
            return render(request,'addProduct.html',{"user":current_user,"form":form})

# users can either add products or milk collection
@login_required
def show_options(request):
    return render(request, 'show_options.html')

# add milk collection data
@login_required
def add_milk(request):
    current_user = request.user
    profiles = UserProfile.get_profile()
    name =  request.POST.get("profile_name")
    for profile in profiles:
        if profile.profile_name.id == current_user.id:
            if request.method == 'POST':
                form = MilkCollectionForm(request.POST)
                if form.is_valid():
                    upload = form.save(commit=False)
                    upload.posted_by = current_user
                    upload.profile = profile
                    upload.save()
                    messages.success(request, f'Hi {name}, Your data has successfully been updated' )
                    return redirect('addProduct')
            else:
                form = MilkCollectionForm()
            return render(request,'addProduct.html',{"user":current_user,"form":form})

# show or display user products
@login_required(login_url="login")
def products(request):
    products2 = Project.objects.filter(posted_by=request.user)
    return render(request, 'products.html', { "products2": products2})

# display user total expenditure
@login_required(login_url="login")
def SalaryModel(request):
        empobj = Project.get_projects().filter(posted_by=request.user)
        return render(request, 'total.html', {"Project":empobj} )

# display current margin not currently working!!!!!
@login_required(login_url="login")
def margin(request):
        empobj = MadeSale.get_sales().filter(juror=request.user)
        return render(request, 'margin.html', {"MadeSale":empobj} )

# calculate user margin
@login_required
def add_user_sales(request , pk):
    current_user = request.user
    user_id = MadeSale.objects.get(id=pk)
    profiles = UserProfile.get_profile()
    for profile in profiles:
        if profile.profile_name.id == current_user.id:
            if request.method == 'POST':
                form = SalesForm(request.POST)
                if form.is_valid():
                    upload = form.save(commit=False)
                    upload.posted_by = current_user
                    upload.profile = profile
                    upload.save()
                    messages.success(request, f'Hi, Your data has successfully been updated' )
                    return redirect('addProduct')
            else:
                form = SalesForm()
            return render(request,'addProduct.html',{"user":current_user,"form":form})

@login_required
def get_total_month(request):
    empobj = MilkCollection.objects.get_or_create(juror=request.user)
    return render(request, 'monthly_total.html', {"MilkCollection":empobj} )



        

DairyManagement/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="description" content="Dento - Dentist &amp; Medical HTML Template">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

  <!-- Title -->
  <title>Hesabu Moneyger</title>

  <!-- Favicon -->
  <link rel="icon" href="{% static 'website/img/core-img/favicon.ico' %}">

  <!-- Core Stylesheet -->
  <link rel="stylesheet" href="{% static 'website/css/style.css' %}">

</head>

<body class="bod">
  <!-- Preloader -->
  <div id="preloader">
    <div class="preload-content">
      <div id="dento-load"></div>
    </div>
  </div>

  <!-- ***** Header Area Start ***** -->
  <header class="header-area">
    <!-- Top Header Area -->
    <div class="top-header-area">
      <div class="container h-100">
        <div class="row h-100 align-items-center">
          <!-- Top Content -->
          <div class="col-6 col-md-9 col-lg-8">
            <div class="top-header-content">
              <a href="{% url 'DairyManagement:home' %}" data-toggle="tooltip" data-placement="bottom" title="Ruaka, Carrefour, Nairobi, Kenya"><i class="fa fa-map-marker"></i> <span>Ruaka, Carrefour, Nairobi, Kenya</span></a>
              <a href="{% url 'DairyManagement:home' %}" data-toggle="tooltip" data-placement="bottom" title="info@hesabumoneyger.co.ke"><i class="fa fa-envelope"></i> <span>info@hesabumoneyger.co.ke</span></a>
            </div>
          </div>
          <!-- Top Header Social Info -->
          <div class="col-6 col-md-3 col-lg-4">
            <div class="top-header-social-info text-right">
              <a  target="_blank" data-toggle="tooltip" data-placement="bottom" title="Facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" target="_blank" data-toggle="tooltip" data-placement="bottom" title="Twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" target="_blank" data-toggle="tooltip" data-placement="bottom" title="Google Plus"><i class="fa fa-google-plus"></i></a>
              <a href="#" target="_blank" data-toggle="tooltip" data-placement="bottom" title="Linkedin"><i class="fa fa-linkedin"></i></a>
              <a href="#"target="_blank" data-toggle="tooltip" data-placement="bottom" title="Pinterest"><i class="fa fa-pinterest"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Top Header End -->

    <!-- Main Header Start -->
    <div class="main-header-area">
      <div class="classy-nav-container breakpoint-off">
        <div class="container">
          <!-- Classy Menu -->
          <nav class="classy-navbar justify-content-between" id="dentoNav">

            <!-- Logo -->
            <a class="nav-brand" href="{% url 'DairyManagement:home' %}"><img src="{% static 'website/img/core-img/logo.png' %}" alt="" width="180px" height="180px"></a>

            <!-- Navbar Toggler -->
            <div class="classy-navbar-toggler">
              <span class="navbarToggler"><span></span><span></span><span></span></span>
            </div>

            <!-- Menu -->
            <div class="classy-menu">

              <!-- Close Button -->
              <div class="classycloseIcon">
                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
              </div>

              <!-- Nav Start -->
              <div class="classynav">
                <ul id="nav">
                  <li><a href="{% url 'DairyManagement:home' %}">Home</a></li>
                  <li><a href="#">Pages</a>
                    <ul class="dropdown">
                      <li><a href="{% url 'DairyManagement:home' %}">- Home</a></li>
                      <li><a href="#">- About Us</a></li>
                      <li><a href="#">- Service</a></li>
                      <li><a href="#">- Pricing</a></li>
                      <li><a href="#">- Blog</a></li>
                      <li><a href="#">- Blog Details</a></li>
                      <li><a href="#">- Contact</a></li>
                      <li><a href="#">- Dropdown</a>
                        <ul class="dropdown">
                          <li><a href="#">- Dropdown Item</a></li>
                          <li><a href="#">- Dropdown Item</a>
                            <ul class="dropdown">
                              <li><a href="#">- Even Dropdown</a></li>
                              <li><a href="#">- Even Dropdown</a></li>
                              <li><a href="#">- Even Dropdown</a></li>
                              <li><a href="#">- Even Dropdown</a></li>
                            </ul>
                          </li>
                          <li><a href="#">- Dropdown Item</a></li>
                          <li><a href="#">- Dropdown Item</a></li>
                        </ul>
                      </li>
                    </ul>
                  </li>
                  <li><a href="#">About</a></li>
                  <li><a href="#">Service</a></li>
                  <li><a href="#">Pricing</a></li>
                  <li><a href="#">Blog</a>
                    <ul class="dropdown">
                      <li><a href="#">- Blog</a></li>
                      <li><a href="#">- Blog Details</a></li>
                    </ul>
                  </li>
                  <li><a href="#">Contact</a></li>
                </ul>
              </div>
              <!-- Nav End -->
            </div>

            <!--  Button -->
            <a  href="{% url 'DairyManagement:register' %}" class="btn dento-btn booking-btn">Register</a>
            <a href="{% url 'DairyManagement:login' %}" class="btn dento-btn booking-btn">Login</a>
          </nav>
        </div>
      </div>
    </div>
  </header>
  <!-- ***** Header Area End ***** -->

  {% block content %}
  {% endblock %}
  <div class="container-1">
    <div class="box-1">
      <img src="{% static 'images/agri1.jpg' %}" alt="Avatar" style="width: 100%;">
      <h3>Farm Management</h3>
      <p>Farming can be tedious, whether small, medium or large.
        Technology is effective in eliminating most of these challenges. Keeping track of your equipment status,
        re-servicing broken equipments and being every aware of cent spent can be daunting, especially if you consider
        the bulkiness of farm work itself. We cannot eliminate all your work, but we can help with the most important factor of them all.
        That is, recording keeping. Track down to your every last spent shilling. We will do maths for you. Go paperless!
      </p>
      <a class="btn btn-sm btn-block bg-dark" style="color: black;"  href="{% url 'DairyManagement:products' %}"> Farm Moneyger </a>
    </div>

    <div class="box-2">
      <img src="{% static 'images/diary.jpg' %}" alt="Avatar" style="width: 100%;">
      <h3>Dairy Farm Management</h3>
      <p>Dairy Farming isn't any easier. But with a Book Keeping Application, its like you have fifty percent of the work
        needed to make sure you are not running at a loss, a profit? That would both be our joy. So, get your receipts, and just save it on the cloud.
        if you are willing to invest. Think of doing it smartly, by automating book record keeping. Keep track of every single cent kept.
        Go paperless!
      </p>
      <a class="btn btn-sm btn-block bg-white" style="color: black;"  href="{{profile}}"> Dairy Moneyger </a>
    </div>

    <div class="box-3">
      <img  src="{% static 'images/poultry.jpg' %}" alt="Avatar" style="width: 100%;">
      <h3>Poultry Farm Management</h3>
      <p>Poultry Farming requires grit and persistence, this is especially true at both the preparation and the brooding stage.
        You are constantly purchasing new equipement, vaccines, chicken feed and this list isn't exhaustive. You have no other option to do so
        if you are willing to invest. Think of doing it smartly, by automating book record keeping. Keep track of every single cent kept.
        Go paperless!
      </p>
      <a class="btn btn-sm btn-block bg-dark" style="color: black;"  href="#"> Poultry Management </a>
    </div>
  </div>

  <!-- ***** Footer Area Start ***** -->
  <footer class="footer-area bg-img bg-gradient-overlay" style="background-image: static 'website/img/bg-img/3.jpg' ">
    <div class="container">
      <div class="row">
        <!-- Single Footer Widget -->
        <div class="col-12 col-sm-6 col-lg-4">
          <div class="single-footer-widget">
            <a href="{% url 'DairyManagement:home' %}" class="d-block mb-4"><img src="{% static 'website/img/core-img/logo.png' %}" width="180px" height="180px" alt=""></a>
            <p>We are Hesabu Moneyger, helping go paperless.</p>
            <div class="footer-contact">
              <p><i class="icon_pin"></i> Ruaka, Carrefour, Nairobi, Kenya</p>
              <li><p><i class="icon_phone"></i> +254 740 636 175</p></li>
              <li><p><i class="icon_phone"></i> +254 751 856 900</p></li>
              <li><p><i class="icon_phone"></i> 0202428104</p></li>
              <p><i class="icon_mail"></i> info@hesabumoneyger.co.ke</p>
            </div>
          </div>
        </div>

        <!-- Single Footer Widget -->
        <div class="col-12 col-sm-6 col-lg">
          <div class="single-footer-widget">
            <!-- Widget Title -->
            <h5 class="widget-title">What can we do?</h5>

            <!-- Opening Hours -->
            <ul class="opening-hours">
              <li><span>Keep track of your margins</span> <span>Automation</span></li>
              <li><span>Secure your data</span> <span>Security</span></li>
              <li><span>Data cloud storage</span> <span>1000%</span></li>
              <li><span>Your paperless business</span> <span>100%</span></li>
            </ul>
          </div>
        </div>

        <!-- Single Footer Widget -->
        <div class="col-12 col-sm-6 col-lg">
          <div class="single-footer-widget">
            <!-- Widget Title -->
            <h5 class="widget-title">Quick Link</h5>

            <!-- Quick Links Nav -->
            <nav>
              <ul class="quick-links">
                <li><a href="#">About</a></li>
                <li><a href="#">FAQs</a></li>
                <li><a href="#">Contact</a></li>
                <li><a href="#">Policy</a></li>
                <li><a href="#">News</a></li>
                <li><a href="#">Advisors</a></li>
                <li><a href="#">Careers</a></li>
                <li><a href="#">Dentist</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">Legals</a></li>
                <li><a href="#">Booking</a></li>
              </ul>
            </nav>
          </div>
        </div>

        <!-- Single Footer Widget -->
        <div class="col-12 col-sm-6 col-lg">
          <div class="single-footer-widget">
            <!-- Widget Title -->
            <h5 class="widget-title">Newsletter</h5>

            <p>We will send out weekly newest article and some great offers</p>
            <!-- Newsletter Form -->
            <div class="footer-newsletter-form">
              <form action="#" method="post">
                <input type="email" name="nl-email" value="" placeholder="Email Address">
                <button type="submit"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
              </form>
            </div>

            <!-- Social Info -->
            <div class="footer-social-info">
              <a href="#" target="_blank" data-toggle="tooltip" data-placement="bottom" title="Facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" target="_blank" data-toggle="tooltip" data-placement="bottom" title="Twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" target="_blank" data-toggle="tooltip" data-placement="bottom" title="Google Plus"><i class="fa fa-google-plus"></i></a>
              <a href="#" target="_blank" data-toggle="tooltip" data-placement="bottom" title="Linkedin"><i class="fa fa-linkedin"></i></a>
              <a href="#"target="_blank" data-toggle="tooltip" data-placement="bottom" title="Pinterest"><i class="fa fa-pinterest"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Copywrite Area -->
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="copywrite-content">

          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- ***** Footer Area End ***** -->

  <!-- ******* All JS ******* -->
  <!-- jQuery js -->
  <script src="{% static 'website/js/jquery.min.js' %}"></script>
  <!-- Popper js -->
  <script src="{% static 'website/js/popper.min.js' %}"></script>
  <!-- Bootstrap js -->
  <script src="{% static 'website/js/bootstrap.min.js' %}"></script>
  <!-- All js -->
  <script src="{% static 'website/js/dento.bundle.js' %}"></script>
  <!-- Active js -->
  <script src="{% static 'website/js/default-assets/active.js' %}"></script>

</body>

</html>

DairyManagement/templates/margin.html
{% load static %}
<!DOCTYPE html>
<html></html>
<head>
    <title>Total</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function(){
           var empsalary;
           var totalsalary = 0
           $('td:nth-child(3)').each(function(){
                empsalary=$(this).html();
                totalsalary+=parseInt(empsalary);
                $('#totalsalary').text(totalsalary);
           });

        });


    </script>
</head>
<head>
    <nav class="navbar" style="margin-left: auto;">
        <ul class="ul" style="margin-left: auto;">
            <li class="li"><a href="{% url 'DairyManagement:user' %}">Home</a></li>
            <li class="li"><a href="{% url 'DairyManagement:total' %}">Total</a></li>
            <li class="li"><a href="{% url 'DairyManagement:margin' %}">Margin</a></li>

            
            <!-- For DevelopmentPurposes -->

            <li class="li"><a href="http://127.0.0.1:8000/admin/">Admin Dashboard</a></li> 
            <li class="li"><a href="{% url 'DairyManagement:monthlyTotal' %}">MilkTotal</a></li>
        </ul>
    </nav>
    <center>
        <h1>Total Sum</h1>
    </center>
    <hr/>
    <table border="1" style="text-align: center;">
        <tr>
            <th>User</th>
            <th>Sales</th>
            <th>Current Margin</th>
            <th>Date Created</th>
        </tr>
        {% for result in MadeSale %}
        <tr>
            <td>{{result.juror}}</td>
            <td>{{result.sales}}</td>
            <td>{{result.margin}}</td>
            <td>{{result.date_created}}</td>
            
        </tr>
        {% endfor %}
        <tr>
            <td colspan="5">Total</td>
            <td id='totalsalary' style="font-weight: bold;"></td>
        </tr>
    </table>

</head>
</html>

DairyManagement/templates/show_options.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title class="hesabu">Hesabu Moneyger</title>
        <meta charset="utf-8">
        <link rel="stylesheet" href="{% static 'user_style.css' %}">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Big+Shoulders+Inline+Text:wght@300&display=swap" rel="stylesheet">
    </head>
    {% block content %}
    {%endblock%}
    <body>
        <p>Would You like to add products or milk collection ?</p>
      <div class="container-1">
        <div class="box-1">
          <img class="img" src="{% static 'images/agri1.jpg' %}" alt="Avatar" style="width: 100%;">
          <h3>Add Products</h3>
          <p>Farming can be tedious, whether small, medium or large.
            Technology is effective in eliminating most of these challenges. Keeping track of your equipment status,
            re-servicing broken equipments and being every aware of cent spent can be daunting, especially if you consider
            the bulkiness of farm work itself. We cannot eliminate all your work, but we can help with the most important factor of them all.
            That is, recording keeping. Track down to your every last spent shilling. We will do maths for you. Go paperless!
          </p>
          <a class="btn btn-sm btn-block bg-dark" style="color: black;"  href="{% url 'DairyManagement:addProduct' %}"> Add </a>
          
          <a class="btn btn-sm btn-danger"  href="{% url 'DairyManagement:total' %}"> View Total </a>
        </div>

        <div class="box-2">
          <img src="{% static 'images/diary.jpg' %}" alt="Avatar" style="width: 100%;">
          <h3>Add Milk Data</h3>
          <p>Dairy Farming isn't any easier. But with a Book Keeping Application, its like you have fifty percent of the work
            needed to make sure you are not running at a loss, a profit? That would both be our joy. So, get your receipts, and just save it on the cloud.
            if you are willing to invest. Think of doing it smartly, by automating book record keeping. Keep track of every single cent kept.
            Go paperless!
          </p>
          <a class="btn btn-sm btn-danger"  href="{% url 'DairyManagement:milkData' %}"> Add </a>
          
          <a class="btn btn-sm btn-danger"  href="{% url 'DairyManagement:total' %}"> View Total </a>
        </div>
      </div>
    </body>
</html>